DIRS =  \
  7z\~ \
  Arj\~ \
  BZip2\~ \
  Cab\~ \
  Chm\~ \
  Cpio\~ \
  Deb\~ \
  GZip\~ \
  Iso\~ \
  Lzh\~ \
  Nsis\~ \
  Pk3\~ \
  Rar\~ \
  RPM\~ \
  Split\~ \
  Tar\~ \
  Z\~ \
  Zip\~ \

all: $(DIRS)

$(DIRS):
!include "../SubBuild.mak"
